=== dimitrijekaranfilovic/xml-veb-servisi/docs/xsd/interesovanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://xmlprojekat/interesovanje"
    xmlns="http://xmlprojekat/interesovanje">

    <xs:element name="interesovanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="licne_informacije">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="drzavljanstvo" type="xs:string"/>
                            <xs:element name="jmbg">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="13"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ime" type="xs:string"/>
                            <xs:element name="prezime" type="xs:string"/>
                            <xs:element name="kontakt">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="email" type="xs:string"/>
                                        <xs:element default="" name="broj_mobilnog" type="xs:string"/>
                                        <xs:element name="broj_fiksnog" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="davalac_krvi" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="odabrana_lokacija_primanja_vakcine" type="xs:string"/>
                <xs:element name="odabir_proizvodjaca">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1">
                            <xs:element maxOccurs="unbounded" name="proizvodjac">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="odabran" type="xs:boolean"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="datum" type="xs:date"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dimitrijekaranfilovic/xml-veb-servisi/docs/xsd/generisano_interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<interesovanje xmlns="http://xmlprojekat/interesovanje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:za="https://www.bilgejc.rs/zajednicko"
    xsi:schemaLocation="http://xmlprojekat/interesovanje interesovanje.xsd">
    <licne_informacije>
        <drzavljanstvo>DRZAVLJANIN_REPUBLIKE_SRBIJE</drzavljanstvo>
        <za:jmbg>1231231231231</za:jmbg>
        <kontakt>
            <za:broj_fiksnog>021-123-123</za:broj_fiksnog>
            <za:broj_mobilnog >060721321</za:broj_mobilnog>
            <za:email >marko@gmail.com</za:email>
        </kontakt>
        <puno_ime>
            <za:ime>Rastko</za:ime>
            <za:prezime>Petrovic</za:prezime>
        </puno_ime>
        <davalac_krvi>true</davalac_krvi>
    </licne_informacije>
    <odabrana_lokacija_primanja_vakcine></odabrana_lokacija_primanja_vakcine>
    <odabrani_proizvodjaci>
        <proizvodjac>Bilo koja</proizvodjac>
    </odabrani_proizvodjaci>
</interesovanje>

=== dimitrijekaranfilovic/xml-veb-servisi/docs/generisani_xml/generisano_interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<interesovanje xmlns="https://www.vakcinacija.rs/interesovanje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:za="https://www.vakcinacija.rs/zajednicko"
    xsi:schemaLocation="http://www.vakcinacija.rs/interesovanje ../xsd/interesovanje.xsd">
    <licne_informacije>
        <drzavljanstvo>DRZAVLJANIN_REPUBLIKE_SRBIJE</drzavljanstvo>
        <jmbg>3101000230504</jmbg>
        <kontakt>
            <za:broj_fiksnog>021123123</za:broj_fiksnog>
            <za:broj_mobilnog >060721321</za:broj_mobilnog>
            <za:email >marko@gmail.com</za:email>
        </kontakt>
        <puno_ime>
            <za:ime>Rastko</za:ime>
            <za:prezime>Petrovic</za:prezime>
        </puno_ime>
        <davalac_krvi>true</davalac_krvi>
    </licne_informacije>
    <odabrana_lokacija_primanja_vakcine></odabrana_lokacija_primanja_vakcine>
    <odabrani_proizvodjaci>
        <proizvodjac>Bilo koja</proizvodjac>
    </odabrani_proizvodjaci>
</interesovanje>
