=== dimitrijekaranfilovic/xml-veb-servisi/docs/xsd/izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="izvestaj_o_imunizaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element default="0" name="podneto_dokumenata_o_interesovanju"
                    type="xs:nonNegativeInteger"/>
                <xs:element default="0" name="primljeno_zahteva_za_sertifikat"
                    type="xs:nonNegativeInteger"/>
                <xs:element default="0" name="izdato_zahteva_za_sertifikat"
                    type="xs:nonNegativeInteger"/>
                <xs:element name="date_doze_vakcina">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="data_doza">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="redni_broj" type="xs:positiveInteger"/>
                                        <xs:element default="0" name="broj_datih_doza"
                                            type="xs:nonNegativeInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="raspodela_po_proizvodjacima">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="stavka">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="proizvodjac">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="0"/>
                                                  <xs:maxLength value="100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element default="0" name="broj_doza"
                                            type="xs:nonNegativeInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="od" type="xs:date" use="required"/>
            <xs:attribute name="do" type="xs:date" use="required"/>
            <xs:attribute name="datum_izdavanja" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dimitrijekaranfilovic/xml-veb-servisi/docs/generisani_xml/generisani_izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<izvestaj_o_imunizaciji xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/izvestaj_o_imunizaciji.xsd" 
    od="2021-08-01" 
    do="2021-09-01" 
    datum_izdavanja="2021-09-11">
    <podneto_dokumenata_o_interesovanju></podneto_dokumenata_o_interesovanju>
    <primljeno_zahteva_za_sertifikat></primljeno_zahteva_za_sertifikat>
    <izdato_zahteva_za_sertifikat></izdato_zahteva_za_sertifikat>
    <date_doze_vakcina>
        <data_doza>
            <redni_broj>1</redni_broj>
            <broj_datih_doza>1023</broj_datih_doza>
        </data_doza>
    </date_doze_vakcina>
    <raspodela_po_proizvodjacima>
        <stavka>
            <proizvodjac>Pfizer</proizvodjac>
            <broj_doza>1023</broj_doza>
        </stavka>
    </raspodela_po_proizvodjacima>
</izvestaj_o_imunizaciji>

=== dimitrijekaranfilovic/xml-veb-servisi/sluzbenici/src/main/resources/schemas/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<izvestaj_o_imunizaciji xmlns="https://www.vakcinacija.rs/izvestaj_o_imunizaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.vakcinacija.rs/izvestaj_o_imunizaciji izvestaj_o_imunizaciji.xsd">
    <periodOd>2021-10-10</periodOd>
    <periodDo>2021-10-10</periodDo>
    <datum_izdavanja>2021-10-10</datum_izdavanja>
    <podneto_dokumenata_o_interesovanju>1</podneto_dokumenata_o_interesovanju>
    <primljeno_zahteva_za_sertifikat>1</primljeno_zahteva_za_sertifikat>
    <izdato_zahteva_za_sertifikat>1</izdato_zahteva_za_sertifikat>
    <date_doze_vakcina>
        <data_doza>
            <redni_broj>1</redni_broj>
            <broj_datih_doza>1</broj_datih_doza>
        </data_doza>
    </date_doze_vakcina>
    <raspodela_po_proizvodjacima>
        <stavka>
            <proizvodjac>Pfizer</proizvodjac>
            <broj_doza>2</broj_doza>
        </stavka>
    </raspodela_po_proizvodjacima>
</izvestaj_o_imunizaciji>
